### ISSUE TITLE
Variable names dont match

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/MetOfficeDataHub#58]
Two variables in
`s3://nowcasting-nwp-development/data/latest.netcdf`
- r2
- s

That are not in `gs://solar-pv-nowcasting-data/NWP/UK_Met_Office/UKV_intermediate_version_3.zarr .`
Is the latter just too old? Did the variables change name?

We probably need to rename some in the Live Data Consumer

**Comment by devsjc** [comment]
I believe the latter is old - I think `version_7.zarr` is the latest dataset that is being used for training.

**Comment by peterdudfield** [comment]
thanks great stuff
