### ISSUE TITLE
Save as Zarr

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/MetOfficeDataHub#59]
## Detailed Description
 I want to make it a .zarr  file with chunks that include all the variables and all the steps. We could very well have the two formats (latest.netcdf and latest.zarr). If my tests are correct this will load the NWP data tens of times faster, which is the current bottleneck.

## Context
Speed up site level forecasts

## Possible Implementation
See [save](https://github.com/openclimatefix/MetOfficeDataHub/blob/main/metofficedatahub/multiple_files.py#L259) method, and yea just both `netcdf` and `zarr`. The code looks already set up save a `zarr` file

**Comment by simlmx** [comment]
Done in #62 
Follow up fixes in #63.
