### ISSUE TITLE
where does 'wind-direction-from-which-blowing-surface-adjusted' go?

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/MetOfficeDataHub#70]
## Detailed Description
I can see in the logs that this data field is pulled, but then when the datafield are merged it seems to disappear

![Screenshot 2023-03-13 at 19 32 22](https://user-images.githubusercontent.com/34686298/224812959-6e05a077-96cd-4d1f-996a-4bdd70ac69de.png)

## Context
Would be good to have this for National forecast

## Possible Implementation
not sure

**Comment by peterdudfield** [comment]
Might be one for you @devsjc?

**Comment by peterdudfield** [comment]
One solution could be to add
```
"wind-direction-from-which-blowing-surface-adjusted": {"unknown": "wdir10"},
```

to `variable_name_translation`

**Comment by devsjc** [comment]
From NWP order `uk-5params-35steps`, the parameter `wind-direction-from-which-blowing-surface-adjusted` comes in with the `shortName` of `unknown`. The above would fix it, however the short name would be at odds with the CEDA data, in which the `shortName` for the same parameter is `10wdir`

**Comment by peterdudfield** [comment]
Thanks @devsjc . Ill got for it then as I think `10wdir` is close enough to `widr10`
