### ISSUE TITLE
`Sde` to `sd`

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/MetOfficeDataHub#71]
@devsjc do you know the different between these tow channel names. 

I'm working with the national forecast and in the training data, we have used `sde`, but live it seems to be `sd`. 

One option is just to rename - https://github.com/openclimatefix/gradboost_pv/pull/35, but I know thats not ideal

Thanks for your help @devsjc

**Comment by devsjc** [comment]
`sd` is from the met office live data, it's the Snow Depth Water Equivalent in and it's measured in `kgm-2`
`sde`is from ceda, also snow depth water equivalent, but this one is measured in `m`

They differ by a factor of ~1000

**Comment by peterdudfield** [comment]
thanks, and do you know if on `CEDA` `sd` is available, or if `sde` is available live?

**Comment by devsjc** [comment]
So far as I can tell, they are exclusive to each platform - `sde` in `m` is all CEDA has to offer, and `sd` in `kg m-2` is all MetOffice can provide. There is a caveat in that there are two variables from CEDA which are completely unknown (both to me and by name and attribute when loaded) which could be `sd` but also could be absolutely anything else!

**Comment by peterdudfield** [comment]
thanks @devsjc . I will clsoe this now as we dont use this in the model anymore
